#define PIL 0
#define COM 1
#define SCI 2
#define SOC 3
#define CLO 4
#define LEAD 5
#define REN 6
#define MEC 7
#define ABL 8
#define INTU 9
#define INTE 10
#define TEC 11
#define INN 12
#define CHA 13
#define COMM 14
#define DEX 15
#define DMG 0