const char *hudstatToCommodity(int hudstat);
const char* gunRangeColour(int totalGuns, int gunsInRange);
const char* printShip(int ship);
const char* securityStatus();
inline int fExists(char *f);
int *hudstatToQuantity(int hudstat);
int cargoLeft();
int checkCapacity(int hudstat, int quantity, int ship);
int derelictAtTile(int coord);
int enemyAtTile(int coord);
int getMapTile(int coord, int mapType);
int hudstatToCapacity(int hudstat);
int initEnemy(int died);
int rangeCheck(int scanTarget, int scans);
int percentile();
int preGameMenu();
int printAt(int x, int y, const char *fmt, ...);
int printLinesAt(int x, int y, const char *str);
int printfLinesAt(int x, int y, const char *fmt, ...);
int randomNumber(int max);
int weaponsCheck(int scanTarget);
int inRange(int scanTarget, int mapIndex);
int spawnEnemy(int edgeOfSpace);
int tryToBuy(int quantity, int price, int hudstat);
int tryToSell(int quantity, int price, int hudstat);
static char* charColour(int mapTile, int scanTarget, int mapIndex);
static char* hudColours(int currentHud, int maxHud);
static char* prefix(int arrayValue, char unit);
static char* printBuySell(char buySell, int commodity, int quantity, int costProfit, int shipCost);
static char* weaponStatus();
void HUD(int startX, int startY);
void achievementsMenu();
void choiceMenu(int debug);
void clean ();
void comLog(int x, int y);
void damageReport(int damage, int player);
void divertPower(int quantity);
void drawWindow(int x, int y, int w, int h);
void enemyMovement();
void fire(int playerFiring);
void firetorpedo();
void generateSystem();
void healthBars();
void help();
void hitAnim(int playerHit);
void initStats(int debug);
void initialize(int whichArray);
void loot();
void minimalHUD(int startX, int startY);
void move(char toWhere);
void printMap(int scanTarget);
void printProgressBar(int skillSlot);
void rangeMap(int scanTarget);
void scan(int scanTarget);
void seed();
void shipDestroyed();
void skillsHUD(int x, int page);
void test();

